<a href="https://colab.research.google.com/github/sijuswamy/Python-for-Datascience/blob/main/1_Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **`Numpy` Library for Data science**

`NumPy` is a commonly used Python data analysis package. By using `NumPy`, you can speed up your workflow, and interface with other packages in the Python ecosystem, like scikit-learn, that use NumPy under the hood. NumPy was originally developed in the mid 2000s, and arose from an even older package called Numeric. This longevity means that almost every data analysis or machine learning package for Python leverages NumPy in some way.



## What is NumPy for a Python coder?
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.

It is the fundamental package for scientific computing with Python. It contains various features including these important ones:

*  A powerful N-dimensional array object
* Sophisticated (broadcasting) functions
* Tools for integrating C/C++ and Fortran code
* Useful linear algebra, Fourier transform, and random number capabilities
* Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data.
* Arbitrary data-types can be defined using Numpy which allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

## Loading `Nupy` library in python

Using `import` method we can load the library in Python with instance as:

In [ ]:
import numpy as np

Note: All the examples discussed below will not run on an online IDE.

# 1. Arrays in `NumPy`: 
`NumPy`’s main object is the homogeneous multidimensional array.

* It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
* In `NumPy` dimensions are called axes. The number of axes is rank.
`NumPy`’s array class is called ndarray. It is also known by the alias array.

**Example**
```
[[ 1, 2, 3],
 [ 4, 2, 5]]
Here,
rank = 2 (as it is 2-dimensional or it has 2 axes)
first dimension(axis) length = 2, second dimension has length = 3
overall shape can be expressed as: (2, 3)
```



## Code example:

In [ ]:
# Python program to demonstrate 
# basic array characteristics
import numpy as np
  
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
  
# Printing type of arr object
print("Array is of type: ", type(arr))
  
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
  
# Printing shape of array
print("Shape of array: ", arr.shape)
  
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
  
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  <U21


## 2. Array creation: 

There are various ways to create arrays in NumPy.

* For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.
* Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.
>For example: np.zeros, np.ones, np.full, np.empty, etc.

* To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.
**arange()**: returns evenly spaced values within a given interval. step size is specified.
**linspace()**: returns evenly spaced values within a given interval. num no. of elements are returned.

* Reshaping array: We can use reshape method to reshape an array. Consider an array with shape $(a_1, a_2, a_3,\ldots , a_N)$. We can reshape and convert it into another array with shape $(b_1, b_2, b_3,\ldots, b_M)$. The only required condition is:
$$a_1 \times a_2 \times a_3\times \ldots \times a_N = b_1 \times b_2 \times b_3\times \ldots \times b_M$$

  (i.e original size of array remains unchanged.)
  
* Flatten array: We can use flatten method to get a copy of array collapsed into one dimension. It accepts order argument. Default value is ‘C’ (for row-major order). Use ‘F’ for column major order.
Note: Type of array can be explicitly defined while creating array.



In [ ]:
# Python program to demonstrate
# array creation techniques
import numpy as np

# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)

# Creating array from tuple
b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)

# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)

# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s."
			"Array type is complex:\n", d)

# Create an array with random values
e = np.random.random((2, 2))
print ("\nA random array:\n", e)

# Create a sequence of integers
# from 0 to 30 with steps of 5
f = np.arange(0, 30, 5)
print ("\nA sequential array with steps of 5:\n", f)

# Create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)
print ("\nA sequential array with 10 values between"
										"0 and 5:\n", g)

# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
				[5, 2, 4, 2],
				[1, 2, 0, 1]])

newarr = arr.reshape(2, 2, 3)

print ("\nOriginal array:\n", arr)
print ("Reshaped array:\n", newarr)

# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()

print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)


Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed tuple:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

A random array:
 [[0.44092229 0.43413435]
 [0.35751754 0.0576922 ]]

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]

A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


# Operations on Numpy Arrays

1. Array Indexing: Knowing the basics of array indexing is important for analysing and manipulating the array object. NumPy offers many ways to do array indexing.

  a. Integer array indexing: In this method, lists are passed for indexing for each dimension. One to one mapping of corresponding elements is done to construct a new arbitrary array.
  b. Boolean array indexing: This method is used when we want to pick elements from array which satisfy some condition.



In [ ]:
# picking second element in first row of the array `arr`

element=arr[0,1]
print("Original Array:",arr)
print("The second element in first row:\n")
print("Element:",element)
print("The second element in first row and third element in second row:\n")
ele_2=arr[[0,1],[1,2]]
print(ele_2)

Original Array: [[1 2 3]
 [4 5 6]]
The second element in first row:

Element: 2
The second element in first row and third element in second row:

[2 6]


2. Slicing: 
Just like lists in python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.

In [ ]:
# Python program to demonstrate
# indexing in numpy
# An exemplar array
arr = np.array([[-1, 2, 0, 4],
				[4, -0.5, 6, 0],
				[2.6, 0, 7, 8],
				[3, -7, 4, 2.0]])

# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
					"columns(0 and 2):\n", temp)

# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
									"(3, 0):\n", temp)

# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)


Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


4. Basic operations: Plethora of built-in arithmetic functions are provided in NumPy.

  *Operations on single array:* We can use overloaded arithmetic operators to do element-wise operation on array to create a new array. In case of +=, -=, *= operators, the exsisting array is modified.

In [ ]:
# Python program to demonstrate
# basic operations on single array
 
a = np.array([1, 2, 5, 3])
  
# add 1 to every element
print ("Adding 1 to every element:", a+1)
  
# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)
  
# multiply each element by 10
print ("Multiplying each element by 10:", a*10)
  
# square each element
print ("Squaring each element:", a**2)
  
# modify existing array
a *= 2
print ("Doubled each element of original array:", a)
  
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
  
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)


Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


* Unary operators: Many unary operations are provided as a method of ndarray class. This includes sum, min, max, etc. These functions can also be applied row-wise or column-wise by setting an axis parameter.

In [ ]:
# Python program to demonstrate
# unary operators in numpy
arr = np.array([[1, 5, 6],
				[4, 7, 2],
				[3, 1, 9]])

# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",
					arr.max(axis = 1))

# minimum element of array
print ("Column-wise minimum elements:",
						arr.min(axis = 0))

# sum of array elements
print ("Sum of all array elements:",
							arr.sum())

# cumulative sum along each row
print ("Cumulative sum along each row:\n",
						arr.cumsum(axis = 1))


Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


* Binary operators: These operations apply on array elementwise and a new array is created. You can use all basic arithmetic operators like +, -, /, , etc. In case of +=, -=, = operators, the exsisting array is modified.

In [ ]:
# Python program to demonstrate
# binary operators in Numpy
a = np.array([[1, 2],
			[3, 4]])
b = np.array([[4, 3],
			[2, 1]])

# add arrays
print ("Array sum:\n", a + b)

# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)

# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))


Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


* *Universal functions (ufunc):* `NumPy` provides familiar mathematical functions such as $\sin, \cos, \exp$, etc. These functions also operate elementwise on an array, producing an array as output.

>Note: All the operations we did above using overloaded operators can be done using ufuncs like `np.add, np.subtract, np.multiply, np.divide, np.sum`, etc.



In [ ]:
# Python program to demonstrate
# universal functions in numpy
# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))

# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))

# square root of array values
print ("Square root of array elements:", np.sqrt(a))


Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


5. Sorting array: There is a simple `np.sort` method for sorting `NumPy` arrays. Let’s explore it a bit.

In [ ]:
# Python program to demonstrate sorting in numpy
a = np.array([[1, 4, 2],
				[3, 4, 6],
			[0, -1, 5]])

# sorted array
print ("Array elements in sorted order:\n",
					np.sort(a, axis = None))

# sort array row-wise
print ("Row-wise sorted array:\n",
				np.sort(a, axis = 1))

# specify sort algorithm
print ("Column wise sort by applying merge-sort:\n",
			np.sort(a, axis = 0, kind = 'mergesort'))

# Example to show sorting of structured array
# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),
		('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
			
# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
			np.sort(arr, order = 'name'))
			
print ("Array sorted by grauation year and then cgpa:\n",
				np.sort(arr, order = ['grad_year', 'cgpa']))


Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by grauation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


## Advanced operations on `Numpy` arrays

Now let's discusses some more and a bit advanced methods available in `NumPy`.

> **Stacking:** Several arrays can be stacked together along different axes.
1. np.vstack: To stack arrays along vertical axis.
2. np.hstack: To stack arrays along horizontal axis.
3. np.column_stack: To stack 1-D arrays as columns into 2-D arrays.
4. np.concatenate: To stack arrays along specified axis (axis is passed as argument).

In [ ]:
a = np.array([[1, 2],
			[3, 4]])

b = np.array([[5, 6],
			[7, 8]])

# vertical stacking
print("Vertical stacking:\n", np.vstack((a, b)))

# horizontal stacking
print("\nHorizontal stacking:\n", np.hstack((a, b)))

c = [5, 6]

# stacking columns
print("\nColumn stacking:\n", np.column_stack((a, c)))

# concatenation method
print("\nConcatenating to 2nd axis:\n", np.concatenate((a, b), 1))


Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]

Column stacking:
 [[1 2 5]
 [3 4 6]]

Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]


>**Splitting:**For splitting, we have these functions:
1. `np.hsplit`: Split array along horizontal axis.
2. `np.vsplit`: Split array along vertical axis.
3. `np.array_split`: Split array along specified axis.


In [ ]:
a = np.array([[1, 3, 5, 7, 9, 11],
			[2, 4, 6, 8, 10, 12]])

# horizontal splitting
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2))

# vertical splitting
print("\nSplitting along vertical axis into 2 parts:\n", np.vsplit(a, 2))


Splitting along horizontal axis into 2 parts:
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]

Splitting along vertical axis into 2 parts:
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


**Broadcasting:** The term broadcasting describes how `NumPy` treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.
Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are also cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

NumPy operations are usually done element-by-element which requires two arrays to have exactly the same shape. Numpy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints.

The Broadcasting Rule: In order to broadcast, the size of the trailing axes for both arrays in an operation must either be the same size or one of them must be one.

Let us see some examples:

A(2-D array): 4 x 3

B(1-D array):     3

Result      : 4 x 3

A(4-D array): 7 x 1 x 6 x 1

B(3-D array):     3 x 1 x 5

Result      : 7 x 3 x 6 x 5

But this would be a mismatch:

A: 4 x 3

B:     4

The simplest broadcasting example occurs when an array and a scalar value are combined in an operation.
Consider the example given below:



In [ ]:
a = np.array([1.0, 2.0, 3.0])

# Example 1
b = 2.0
print(a * b)

# Example 2
c = [2.0, 2.0, 2.0]
print(a * c)


[2. 4. 6.]
[2. 4. 6.]


We can think of the scalar `b` being stretched during the arithmetic operation into an array with the same shape as `a`. The new elements in `b`, as shown in above figure, are simply copies of the original scalar. Although, the stretching analogy is only conceptual.

`Numpy` is smart enough to use the original scalar value without actually making copies so that broadcasting operations are as memory and computationally efficient as possible. Because Example 1 moves less memory, (`b` is a scalar, not an array) around during the multiplication, it is about 10% faster than Example 2 using the standard `Numpy` on Windows 2000 with one million element arrays!


In above example, the scalar b is stretched to become an array of with the same shape as a so the shapes are compatible for element-by-element multiplication.

Now, let us see an example where both arrays get stretched.

In [ ]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([0.0, 1.0, 2.0])

print(a[:, np.newaxis] + b)


[[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]


 This operation can be shown in the following Figure

![](https://media.geeksforgeeks.org/wp-content/uploads/numpy2.png)

In some cases, broadcasting stretches both arrays to form an output array larger than either of the initial arrays.

**Working with datetime:** Numpy has core array data types which natively support datetime functionality. The data type is called “datetime64”, so named because “datetime” is already taken by the datetime library included in Python.
Consider the example below for some examples:

In [ ]:
# creating a date
today = np.datetime64('2017-02-12')
print("Date is:", today)
print("Year is:", np.datetime64(today, 'Y'))

# creating array of dates in a month
dates = np.arange('2017-02', '2017-03', dtype='datetime64[D]')
print("\nDates of February, 2017:\n", dates)
print("Today is February:", today in dates)

# arithmetic operation on dates
dur = np.datetime64('2017-05-22') - np.datetime64('2016-05-22')
print("\nNo. of days:", dur)
print("No. of weeks:", np.timedelta64(dur, 'W'))

# sorting dates
a = np.array(['2017-02-12', '2016-10-13', '2019-05-22'], dtype='datetime64')
print("\nDates in sorted order:", np.sort(a))


Date is: 2017-02-12
Year is: 2017

Dates of February, 2017:
 ['2017-02-01' '2017-02-02' '2017-02-03' '2017-02-04' '2017-02-05'
 '2017-02-06' '2017-02-07' '2017-02-08' '2017-02-09' '2017-02-10'
 '2017-02-11' '2017-02-12' '2017-02-13' '2017-02-14' '2017-02-15'
 '2017-02-16' '2017-02-17' '2017-02-18' '2017-02-19' '2017-02-20'
 '2017-02-21' '2017-02-22' '2017-02-23' '2017-02-24' '2017-02-25'
 '2017-02-26' '2017-02-27' '2017-02-28']
Today is February: True

No. of days: 365 days
No. of weeks: 52 weeks

Dates in sorted order: ['2016-10-13' '2017-02-12' '2019-05-22']
